Detect Hiera files that are no valid hash
This was reported on slack via @ikonia. with such malformed keys, Hiera
just reports a string:

```
irb(main):002> require 'yaml'
=> true
irb(main):003> yamlargs = (Psych::VERSION >= '4.0') ? { aliases: true } : {}
=> {aliases: true}
irb(main):004> hiera_file='spec/fixtures/hiera/hiera_key_no_value.yaml'
=> "spec/fixtures/hiera/hiera_key_no_value.yaml"
irb(main):005> YAML.load_file(hiera_file, **yamlargs)
=> "prometheus::initstyle:sysv prometheus::node_exporter::init_style:sysv"
irb(main):006>
```

And puppetserver will fail to compile a catalog:

```
Notice: Catalog compiled by ***
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, /etc/puppetlabs/code/environments/***.yaml: file does not contain a valid yaml hash on node ***
Warning: Not using cache on failed catalog
```